version: "3.9"
services:
  database:
    image: 'postgres:latest'
    ports:
      - "5000:5000"
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'clubhouse'